# Generated by Django 4.1.4 on 2023-01-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.ImageField(default='default/default_preview.jpg', upload_to='courses/preview'),
        ),
    ]
