# Generated by Django 4.1.4 on 2023-01-21 12:10

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_course_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='text',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='video',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='content',
            name='object_id',
        ),
        migrations.AddField(
            model_name='content',
            name='contentFile',
            field=models.FileField(blank=True, null=True, upload_to='contents/files'),
        ),
        migrations.AddField(
            model_name='content',
            name='contentImage',
            field=models.FileField(blank=True, null=True, upload_to='contents/images'),
        ),
        migrations.AddField(
            model_name='content',
            name='contentText',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='contentVideo',
            field=models.FileField(blank=True, null=True, upload_to='contents/images'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
