# Generated by Django 4.1.4 on 2023-01-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default/default.png', upload_to='user/profile/avatar'),
        ),
    ]
