# Generated by Django 4.1.4 on 2023-01-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_student_instructor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
