# Generated by Django 4.1.4 on 2023-01-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
